### ISSUE TITLE
Bug: Edit files description fails

### ISSUE THREAD

**Issue by danmisailescu** [eaudeweb/ozone#567] opened 2019-02-01 15:56 UTC
Adding files with dercription work, but edit files description fails. 

Method PUT not allowed.  

This can be tested easily from the application. Modify some descriptions and then press Save.

![_files-1](https://user-images.githubusercontent.com/5540680/52133550-37f8d300-264a-11e9-8482-deb28b9791b2.png)

This the the request format:
![_files-2](https://user-images.githubusercontent.com/5540680/52133581-4810b280-264a-11e9-939d-6be3372f66be.png)

**Comment by sorinstelian** [comment] 2019-02-01 16:50
Pretty much a duplicate of https://github.com/eaudeweb/ozone/issues/560 (which was not a bug :D), which has been solved. Closing.

Also added the ability to modify file name, which could be useful in case of renames.

**Closed by sorinstelian** 2019-02-01 16:50 UTC
Labels: Priority: High
