### ISSUE TITLE
Flags for reporting periods

### ISSUE THREAD

**Issue by melish** [eaudeweb/ozone#167] opened 2018-11-27 10:45 UTC
is_reporting_allowed (default: True) - if party can select this period when creating a new submission. API must raise an error otherwise
is_reporting_open (default: False) - if this is the "current" period. Let's assume there can be multiple current periods (2017,2018 in fixtures). For current periods, lesser restrictions apply (e.g. a superseded submission can be cloned only for current periods).

TODO: 
- [ ] add field to models and serializers
- [ ] update validation in API for create submission and clone submission

**Comment by sorinstelian** [comment] 2018-11-27 11:00
Duplicate of https://github.com/eaudeweb/ozone/issues/168

**Closed by sorinstelian** 2018-11-27 11:00 UTC
