### ISSUE TITLE
Comments/Feedback from demo

### ISSUE THREAD

**Issue by nico4** [eaudeweb/ozone#873] opened 2019-04-19 08:17 UTC
- [x] Submission Info page – the pull down with the country – should be labelled “Address country” or something similar.
- [ ] Submission Info page – Mark “required” fields as such – I believe you had this before and you probably have this for some pages – but when we were running the demo, the required fields were not shown as “required” for Article 7 data forms.
- [x] Submission Info page – where we have “Version (Data entry)” status – swap them do that we get instead “Data entry (version)”.
- [x] One of the columns was labelled “State” – please change to status so that we have consistency in using the word status.
- [ ] In chrome browser, the pull down menus had two arrows – inside the list and the one on the right of the pull down – probably a browser compatibility issue. Please check.
- [ ] Data entry submissions window grows indefinitely – can we make it scrollable instead?
- [x] Title of the whole submission – add the word data after article 7 – so that it reads “2018 Article 7 data submission for Australia”.
- [x] For the Imports/Exports/Non-Party trade forms – the countries column should be labelled “Countries/Regions/Territories”.
- [ ] For all the forms, the “Edit/Delete” icons should be moved to the right – this is the same request we have been making for a while.
- [ ] For the data entry forms, when adding substances, in the pull down for annex groups, add the name of substances next to the “AI”, “AII”, etc. so that it is C/I (HCFCs), A/I (CFCs), A/II (Halons), etc.
- [ ] For the prompt when submitting, use the following text too: “By clicking the OK button, you confirm that all blank cells and all substances not included are considered to have zero values.
- [ ] When prompting to “Leave” page, please use the text “Leave this page” instead of “Leave” or “Leave Page”
- [ ] For the polyol field, we need clear information that “Amounts in pre-blended polyols are not to be included in the amount of total imports”.
- [ ] For RAF, column “A” is missing the A.
- [ ] We have updated the name for Taiwan in the Cntry table so be on the lookout for it.
- [ ] For the Export to PDF – please ensure it is in a new window (my computer behaves OK – could not reproduce the problem on my computer).  However, on the demo computer, we viewed PDF, and then inadvertently closed the whole window.  It could be dependent on the browser together with the browser settings.
- [ ] When we closed the window by mistake, the system did not ask us to confirm that we wanted to exit. 
- [ ] For the “Calculated Amounts” window, can we make it printable and exportable? (Calculated production and consumption)
- [ ] It was proposed to have an autosave implementation – saving every 5 minutes – so that if someone has been typing for long or leave the page for a while, they should not lose their work if electricity goes out – a common occurrence in developing countries.
- [ ] We need for the system to do the following:
- [ ] Automatically acknowledge a submission from a party via email (just saying thank you for the submission, it will be reviewed by the secretariat before finalization) – which means email should be a mandatory field;
- [ ] After finalization by the Secretariat, the system should automatically create an email for the secretariat to edit and send via the system – notifying the party of its findings.  We can send you template text that could be initial text in the email, which then the Secretariat would edit.  If possible, we could have several templates.
- [ ] As mentioned during our teleconference, we might be sending one or two forms – for EUN/CUN nominations – that Parties might be able to complete (not just Secretariat).

**Comment by nico4** [comment] 2019-04-19 08:24
Need more info on :

* In chrome browser, the pull down menus had two arrows – inside the list and the one on the right of the pull down – probably a browser compatibility issue. Please check.

**Comment by nico4** [comment] 2019-04-19 08:25
Data entry submissions window grows indefinitely – can we make it scrollable instead?
 - >
Add pagination to data entry table for parties

**Comment by nico4** [comment] 2019-04-19 08:29
https://cl.ly/c7a3db73e898

Fix word wrap problem

**Comment by nico4** [comment] 2019-04-19 08:39
> We have updated the name for Taiwan in the Cntry table so be on the lookout for it.

@sorinstelian , please update fixtures.

**Comment by nico4** [comment] 2019-04-19 08:48
Hard to implement:

* It was proposed to have an autosave implementation – saving every 5 minutes – so that if someone has been typing for long or leave the page for a while, they should not lose their work if electricity goes out – a common occurrence in developing countries.

**Comment by nico4** [comment] 2019-04-19 08:51
Hard to implement:

* After finalization by the Secretariat, the system should automatically create an email for the secretariat to edit and send via the system – notifying the party of its findings. We can send you template text that could be initial text in the email, which then the Secretariat would edit. If possible, we could have several templates.

**Comment by melish** [comment] 2019-04-19 16:29
Duplicate of #866, closing

**Closed by melish** 2019-04-19 16:29 UTC
Labels: Component: Backend, Component: Vue, Frontend: Small stuff
