### ISSUE TITLE
Edit substance and blend modal 

### ISSUE THREAD

**Issue by razvanMiu** [eaudeweb/ozone#582] opened 2019-02-08 16:21 UTC
How to reproduce:

- Add substance (entity_1)
- Open edit modal for entity_1 and add values in inputs
- Add another substance or blend (entity_2)
- Open edit modal for entity_2 
- You will see that the values for entity_1 are still in the inputs

OBS:
If you add some text in input#decision_critical_uses, or any other input, (in modal) for entity_1 then open modal for entity_2 you will find the same text in input#decision_critical_uses. The problem is that if you want to edit that text you have to click in that input, edit the text, then click outside of it. Also you can't add the same text you added to entity_1; it will not show.

**Comment by nico4** [comment] 2019-03-05 15:08
I cannot reproduce it.

**Comment by melish** [comment] 2019-03-26 09:40
Doesn't seem to happen anymore, closing.

**Closed by melish** 2019-03-26 09:40 UTC
Labels: Component: Vue, Status: In progress
